# Generated by Django 4.2.7 on 2023-12-17 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_consulta', models.CharField(max_length=255)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('temas_relacionados', models.CharField(max_length=255)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('consulta_texto', models.TextField()),
                ('receptor_consulta', models.ForeignKey(limit_choices_to={'staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='ArchivoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='consultas_archivos/')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_consultas', to='app_consulta.consulta')),
            ],
        ),
    ]
