# Generated by Django 4.2.7 on 2023-12-17 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_cuota', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default='december')),
                ('anno_cuota', models.IntegerField(default=2023)),
                ('mes_cuota_vencimiento', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anno_cuota_vencimiento', models.IntegerField(default=2023)),
                ('descripcion', models.CharField(default='Cuota Aigasra Sociedad', max_length=255)),
                ('valor_cuota', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos argentinos'), ('USD', 'Dólares estadounidenses'), ('BRL', 'Reales brasileños')], default='ARS', max_length=15)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
    ]
