# Generated by Django 4.2.7 on 2023-12-17 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contacto_images/')),
                ('cargo', models.CharField(choices=[('director', 'Director'), ('secretario', 'Secretario'), ('subsecretario', 'Subsecretario'), ('editor', 'Editor'), ('tesorero', 'Tesorero'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(choices=[('licenciado', 'Licenciado'), ('tecnico', 'Técnico'), ('arquitecto', 'Arquitecto'), ('doctor', 'Doctor'), ('master', 'Máster'), ('ingeniero', 'Ingeniero'), ('otro', 'Otro')], max_length=20)),
                ('biografia', models.TextField()),
            ],
            options={
                'db_table': 'contacto',
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corto', models.CharField(default='Articulo de Aigasra', max_length=100)),
                ('largo', models.CharField(max_length=255)),
                ('edicion', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(upload_to='novedades_images/')),
                ('bio', models.TextField()),
                ('creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_no_user.contacto')),
            ],
            options={
                'db_table': 'novedad',
            },
        ),
    ]
