# Generated by Django 4.2.7 on 2023-12-17 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AigasraUserBase',
            fields=[
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cuit', models.PositiveIntegerField(blank=True, null=True, verbose_name='CUIT')),
                ('nombre_matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de Matrícula')),
                ('distribuidora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distribuidora')),
                ('domicio_real', models.TextField(blank=True, null=True, verbose_name='Domicilio Real')),
                ('dir_registracion', models.TextField(blank=True, null=True, verbose_name='Dir. de Registración')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('accept_terms', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aceptar términos y condiciones')),
                ('accept_aigasra_info', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aceptar recibir información de Aigasra')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='AigasraUser',
            fields=[
                ('aigasrauserbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_aigasra_user.aigasrauserbase')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
            bases=('app_aigasra_user.aigasrauserbase', models.Model),
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_change_settings', 'Can change settings')],
            },
        ),
    ]
