# Generated by Django 4.2.7 on 2023-12-17 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('short', models.CharField(max_length=50)),
                ('full', models.TextField()),
                ('archivos', models.FileField(blank=True, null=True, upload_to='biblioteca_archivos/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='biblioteca_imagen/')),
            ],
        ),
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Normativa', max_length=100)),
                ('normativa', models.TextField(default='')),
                ('fecha', models.DateField()),
                ('status', models.CharField(choices=[('actualizado', 'Actualizado'), ('vigente', 'Vigente')], default='vigente', max_length=50)),
                ('explicacion', models.TextField(default='')),
                ('link', models.URLField(default='https://www.aigasra.com.ar/educativa')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='curso_imagen/')),
                ('nombre', models.CharField(default='Curso', max_length=100)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.DurationField(default='90 days')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('pospuesto', 'Pospuesto'), ('otro', 'Otro')], default='activo', max_length=50)),
                ('dictado', models.CharField(choices=[('aigasra', 'Aigasra'), ('privado', 'Privado'), ('estatal', 'Estatal'), ('otros', 'Otros')], default='aigasra', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sinopsis', models.CharField(default='Curso generado por Aigasra.', max_length=50)),
                ('detailed', models.TextField(default='')),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='usuarios_cursos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
